// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqO2sVqeFr_6GerzHsZJa20H-9wGfC2w',
    appId: '1:586664850230:web:f6eedd1bab80352599f997',
    messagingSenderId: '586664850230',
    projectId: 'futurelands-bd386',
    authDomain: 'futurelands-bd386.firebaseapp.com',
    storageBucket: 'futurelands-bd386.appspot.com',
    measurementId: 'G-ZDNY7GH5DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgdzhDpSvNkwpT7c1Agf2t-5K7SmPb9qA',
    appId: '1:586664850230:android:5c174b94622873c399f997',
    messagingSenderId: '586664850230',
    projectId: 'futurelands-bd386',
    storageBucket: 'futurelands-bd386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2sEXSppzrA1kCXR0yLSxnhC9hC2t9ak',
    appId: '1:586664850230:ios:f53b81ab87cf3b9a99f997',
    messagingSenderId: '586664850230',
    projectId: 'futurelands-bd386',
    storageBucket: 'futurelands-bd386.appspot.com',
    iosClientId: '586664850230-qsppvodp3o5o6s0r1mnucdb2n3v8tfiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeLand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2sEXSppzrA1kCXR0yLSxnhC9hC2t9ak',
    appId: '1:586664850230:ios:f53b81ab87cf3b9a99f997',
    messagingSenderId: '586664850230',
    projectId: 'futurelands-bd386',
    storageBucket: 'futurelands-bd386.appspot.com',
    iosClientId: '586664850230-qsppvodp3o5o6s0r1mnucdb2n3v8tfiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeLand',
  );
}
